import json
import os

nb_path = 'CODE/RICE_VISION_MAIN_PIPELINE.ipynb'
with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Find indices
cell_features_idx = -1
cell_report_idx = -1
for i, cell in enumerate(nb['cells']):
    src = ''.join(cell.get('source', []))
    if 'REGRESSION_FEATURES' in src:
        cell_features_idx = i
    if 'REGRESSION_REPORT' in src:
        cell_report_idx = i

if cell_features_idx != -1:
    cell_features = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "REGRESSION_FEATURES"},
        "outputs": [],
        "source": [
            "# ==============================================================================\n",
            "# REGRESSION_FEATURES: TRÍCH XUẤT ĐẶC TRƯNG TỪ QUY TRÌNH HÌNH HỌC\n",
            "# ==============================================================================\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import math\n",
            "\n",
            "def assemble_regression_features(bundle, input_records=None, input_metrics=None):\n",
            "    # Resolve defaults to raw aliases at call time\n",
            "    records = input_records if input_records is not None else whole_records\n",
            "    metrics = input_metrics if input_metrics is not None else whole_grain_metrics_list\n",
            "    \n",
            "    if len(records) == 0:\n",
            "        raise ValueError(\"Không tìm thấy hạt lúa nguyên nào (whole grains). Dừng suy luận regression.\")\n",
            "    \n",
            "    if \"INPUT_WEIGHT_G\" not in globals() or INPUT_WEIGHT_G is None:\n",
            "        raise ValueError(\"Thiếu dữ liệu cân nặng thật (INPUT_WEIGHT_G=None). Vui lòng cân chính xác mẫu.\")\n",
            "    actual_weight_g = float(INPUT_WEIGHT_G)\n",
            "    if not np.isfinite(actual_weight_g) or actual_weight_g <= 0:\n",
            "        raise ValueError(f\"Dữ liệu cân nặng không hợp lệ: {actual_weight_g} g\")\n",
            "        \n",
            "    if not metrics:\n",
            "        raise ValueError(\"Không có metrics hạt hợp lệ.\")\n",
            "        \n",
            "    lens_arr = np.array([float(m[\"length_mm\"]) for m in metrics])\n",
            "    wids_arr = np.array([float(m[\"width_mm\"]) for m in metrics])\n",
            "    thks_arr = np.array([float(m[\"thickness_mm\"]) for m in metrics])\n",
            "    area_arr = np.array([float(m[\"area_mm2\"]) for m in metrics])\n",
            "    vols_arr = np.array([float(m[\"volume_mm3\"]) for m in metrics])\n",
            "    \n",
            "    if np.any(~np.isfinite(lens_arr)) or np.any(lens_arr <= 0) or np.any(vols_arr <= 0):\n",
            "        raise ValueError(\"Measurements chứa giá trị NaN, Inf hoặc <= 0.\")\n",
            "        \n",
            "    if \"rice_height_mm\" not in container_info or \"inner_w_px\" not in container_info:\n",
            "        raise ValueError(\"Thiếu thông số container_info (rice_height_mm hoặc inner_w_px).\")\n",
            "        \n",
            "    def calc_stats(arr):\n",
            "        return {\n",
            "            \"Mean\": round(float(np.mean(arr)), 3),\n",
            "            \"Min\": round(float(np.min(arr)), 3),\n",
            "            \"Max\": round(float(np.max(arr)), 3),\n",
            "            \"Std\": round(float(np.std(arr, ddof=0)), 3)\n",
            "        }\n",
            "        \n",
            "    lens_st = calc_stats(lens_arr)\n",
            "    wids_st = calc_stats(wids_arr)\n",
            "    thks_st = calc_stats(thks_arr)\n",
            "    area_st = calc_stats(area_arr)\n",
            "    vols_st = calc_stats(vols_arr)\n",
            "    \n",
            "    from modules.uniformity_evaluator import evaluate_batch_uniformity\n",
            "    batch_uniformity = evaluate_batch_uniformity(vols_arr.tolist())\n",
            "    unif_rate = round(float(batch_uniformity.get(\"uniformity_rate_pct\", 0.0)), 2)\n",
            "    \n",
            "    raw_bulk_volume = float(bulk_volume_mm3)\n",
            "    mean_volume = float(np.mean(vols_arr))\n",
            "    \n",
            "    # Dùng hệ số hybrid của bundle nếu có, ngược lại mặc định 0.62\n",
            "    hybrid_factor = bundle.get(\"hybrid_packing_fraction\", 0.62)\n",
            "    hybrid_estimate = int(round((raw_bulk_volume * hybrid_factor) / mean_volume))\n",
            "    \n",
            "    feat_dict = {\n",
            "        \"Bulk_Rice_Volume_mm3\": round(raw_bulk_volume, 2),\n",
            "        \"Rice_Height_mm\": round(float(container_info[\"rice_height_mm\"]), 2),\n",
            "        \"Weight_g\": actual_weight_g,\n",
            "        \"Empty_Height_mm\": float(EMPTY_HEIGHT_MM),\n",
            "        \"Pixels_Per_mm\": round(float(pixels_per_mm), 2),\n",
            "        \"Container_Detected_Diam_px\": round(float(container_info[\"inner_w_px\"]), 2),\n",
            "        \"Inner_Diameter_mm\": float(INNER_DIAM_MM),\n",
            "        \"Container_Height_mm\": float(CONTAINER_HEIGHT_MM),\n",
            "        \"Whole_Grains_Count\": float(len(records)),\n",
            "        \"Uniformity_Rate_Pct\": unif_rate,\n",
            "        \"Estimated_Total_Seeds_Hybrid\": float(hybrid_estimate),\n",
            "        \n",
            "        \"Grain_Length_mm_Mean\": lens_st[\"Mean\"],\n",
            "        \"Grain_Length_mm_Min\": lens_st[\"Min\"],\n",
            "        \"Grain_Length_mm_Max\": lens_st[\"Max\"],\n",
            "        \"Grain_Length_mm_Std\": lens_st[\"Std\"],\n",
            "        \n",
            "        \"Grain_Width_mm_Mean\": wids_st[\"Mean\"],\n",
            "        \"Grain_Width_mm_Min\": wids_st[\"Min\"],\n",
            "        \"Grain_Width_mm_Max\": wids_st[\"Max\"],\n",
            "        \"Grain_Width_mm_Std\": wids_st[\"Std\"],\n",
            "        \n",
            "        \"Grain_Thickness_mm_Mean\": thks_st[\"Mean\"],\n",
            "        \"Grain_Thickness_mm_Min\": thks_st[\"Min\"],\n",
            "        \"Grain_Thickness_mm_Max\": thks_st[\"Max\"],\n",
            "        \"Grain_Thickness_mm_Std\": thks_st[\"Std\"],\n",
            "        \n",
            "        \"Grain_Area_mm2_Mean\": area_st[\"Mean\"],\n",
            "        \"Grain_Area_mm2_Min\": area_st[\"Min\"],\n",
            "        \"Grain_Area_mm2_Max\": area_st[\"Max\"],\n",
            "        \"Grain_Area_mm2_Std\": area_st[\"Std\"],\n",
            "        \n",
            "        \"Grain_Volume_mm3_Mean\": vols_st[\"Mean\"],\n",
            "        \"Grain_Volume_mm3_Min\": vols_st[\"Min\"],\n",
            "        \"Grain_Volume_mm3_Max\": vols_st[\"Max\"],\n",
            "        \"Grain_Volume_mm3_Std\": vols_st[\"Std\"]\n",
            "    }\n",
            "    \n",
            "    for k, v in feat_dict.items():\n",
            "        if not math.isfinite(v):\n",
            "            raise ValueError(f\"Feature {k} không phải là số hữu hạn: {v}\")\n",
            "            \n",
            "    df = pd.DataFrame([feat_dict], columns=bundle[\"ordered_features\"])\n",
            "    return df\n",
            "\n",
            "print(\"🔄 Đang trích xuất 31 đặc trưng (từ tập RAW)...\")\n",
            "regression_features = assemble_regression_features(regression_bundle)\n",
            "\n",
            "if 'filtered_whole_records' in locals() and filtered_whole_records:\n",
            "    filtered_regression_features = assemble_regression_features(\n",
            "        regression_bundle, \n",
            "        input_records=filtered_whole_records,\n",
            "        input_metrics=filtered_whole_grain_metrics_list\n",
            "    )\n",
            "else:\n",
            "    filtered_regression_features = None\n",
            "    \n",
            "print(f\"✅ Đặc trưng hợp lệ. Hybrid theo bundle: {regression_features['Estimated_Total_Seeds_Hybrid'].iloc[0]}\")\n"
        ]
    }
    nb['cells'][cell_features_idx] = cell_features

if cell_report_idx != -1:
    cell_report = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "REGRESSION_REPORT"},
        "outputs": [],
        "source": [
            "# ==============================================================================\n",
            "# REGRESSION_REPORT: XUẤT KẾT QUẢ VÀ LƯU BÁO CÁO\n",
            "# ==============================================================================\n",
            "if 'regression_result' not in locals():\n",
            "    raise RuntimeError(\"Chưa có kết quả. Vui lòng chạy các Cell phía trên tuần tự.\")\n",
            "\n",
            "metrics = regression_bundle[\"metrics\"]\n",
            "cv_mae = metrics.get(\"cv_summary\", {}).get(\"cv_mae_mean\", \"N/A\")\n",
            "\n",
            "print(\"\\n\" + \"╔\" + \"═\" * 78 + \"╗\")\n",
            "print(\"║\" + \" \" * 22 + \"🤖 KẾT QUẢ DỰ ĐOÁN HỒI QUY (AI)\" + \" \" * 23 + \"║\")\n",
            "print(\"╠\" + \"═\" * 78 + \"╣\")\n",
            "print(f\"║  📸 Tệp ảnh phân tích      : {os.path.basename(IMAGE_PATH):<47} ║\")\n",
            "print(f\"║  ⚖️  Khối lượng mẫu         : {INPUT_WEIGHT_G:<6.2f} gam {'':<46} ║\")\n",
            "print(f\"║  🌾 Số hạt bề mặt ly       : {len(whole_grains):<3} hạt nguyên / {len(cleaned_grains):<3} hạt tổng{'':<18} ║\")\n",
            "print(f\"║  📏 Thể tích khối lúa (V)  : {bulk_volume_mm3:<10,.1f} mm³{'':<33} ║\")\n",
            "print(f\"║  📐 Thể tích 1 hạt nguyên  : {regression_features['Grain_Volume_mm3_Mean'].iloc[0]:<6.2f} mm³ (Raw) {'':<30} ║\")\n",
            "print(\"╠\" + \"═\" * 78 + \"╣\")\n",
            "print(f\"║  DỰ ĐOÁN VẬT LÝ (Cell 9): {str(estimated_seed_count):<5} HẠT (V_bulk * {PACKING_FRACTION} / V_grain_IQR){'':<6} ║\")\n",
            "print(f\"║  DỰ ĐOÁN HỒI QUY (AI)   : \\033[1;32m{regression_result['final_count']:<5}\\033[0m HẠT {'':<39} ║\")\n",
            "print(\"╠\" + \"═\" * 78 + \"╣\")\n",
            "print(f\"║  Thư mục Model: {REGRESSION_MODEL_DIR:<62} ║\")\n",
            "print(f\"║  Mô hình      : {regression_bundle['model'].__class__.__name__:<20} | Scaler: {regression_bundle['scaler'].__class__.__name__ if regression_bundle['scaler'] else 'None':<24} ║\")\n",
            "print(f\"║  Raw Predict  : {regression_result['raw_count']:<20.4f} | Training CV MAE: {cv_mae:<15} ║\")\n",
            "print(\"╚\" + \"═\" * 78 + \"╝\\n\")\n",
            "\n",
            "final_prediction_csv = os.path.join(OUTPUT_REPORT_DIR, \"final_prediction_summary.csv\")\n",
            "prediction_summary_record = {\n",
            "    \"Image_Name\": os.path.basename(IMAGE_PATH),\n",
            "    \"Bulk_Rice_Volume_mm3\": round(float(bulk_volume_mm3), 2),\n",
            "    \"Mean_Grain_Volume_mm3\": round(float(mean_whole_grain_vol) if mean_whole_grain_vol else 0, 2),\n",
            "    \"Whole_Grains_Count\": len(whole_records),\n",
            "    \"Physical_Formula_Estimate\": estimated_seed_count,\n",
            "    \"Linear_Regression_Predicted_Seeds\": regression_result[\"final_count\"],\n",
            "    \"Regression_Predicted_Seeds\": regression_result[\"final_count\"],\n",
            "    \"Regression_Raw_Prediction\": regression_result[\"raw_count\"],\n",
            "    \"Regression_Model\": regression_bundle[\"model\"].__class__.__name__,\n",
            "    \"Regression_Bundle_Dir\": REGRESSION_MODEL_DIR,\n",
            "    \"Regression_Scaler\": regression_bundle[\"scaler\"].__class__.__name__ if regression_bundle[\"scaler\"] else \"None\",\n",
            "    \"Feature_Schema_Version\": regression_bundle[\"schema_version\"],\n",
            "    \"Regression_Feature_Population\": \"raw_valid_cnn_whole\",\n",
            "    \"Physical_Feature_Population\": \"area_iqr_filtered_then_volume_iqr\"\n",
            "}\n",
            "\n",
            "import pandas as pd\n",
            "df_new = pd.DataFrame([prediction_summary_record])\n",
            "df_new.to_csv(final_prediction_csv, index=False, encoding=\"utf-8-sig\")\n",
            "\n",
            "# So sánh raw/filtered\n",
            "feature_csv = os.path.join(OUTPUT_REPORT_DIR, \"regression_input_features.csv\")\n",
            "regression_features.to_csv(feature_csv, index=False, encoding=\"utf-8-sig\")\n",
            "\n",
            "if filtered_regression_features is not None:\n",
            "    comparison_df = pd.DataFrame({\n",
            "        \"Feature\": regression_features.columns,\n",
            "        \"Raw_Value\": regression_features.iloc[0].values,\n",
            "        \"Filtered_Value\": filtered_regression_features.iloc[0].values\n",
            "    })\n",
            "    comparison_df[\"Delta\"] = comparison_df[\"Filtered_Value\"] - comparison_df[\"Raw_Value\"]\n",
            "    comp_path = os.path.join(OUTPUT_REPORT_DIR, \"regression_feature_comparison.csv\")\n",
            "    comparison_df.to_csv(comp_path, index=False, encoding=\"utf-8-sig\")\n",
            "    print(f\"💾 Đã lưu comparison features vào: {comp_path}\")\n",
            "\n",
            "print(f\"💾 Đã lưu summary vào: {final_prediction_csv}\")\n",
            "print(f\"💾 Đã lưu 31 features (raw) vào: {feature_csv}\")\n"
        ]
    }
    nb['cells'][cell_report_idx] = cell_report

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print("Notebook Cell 14 and 16 rewritten safely.")
